[tool.ruff]
line-length = 79
target-version = "py310"
exclude = [".*", "**/__pycache__/", "*.toml", "*.txt", "*.ini", "**/migrations/"]

[tool.mypy]
python_version = "3.10"
exclude = [".*", "**/__pycache__/", "*.toml", "*.txt", "*.ini", "**/migrations/"]

[tool.pytype]
python_version = "3.10"
exclude = [".*", "**/__pycache__/", "*.toml", "*.txt", "*.ini", "**/migrations/"]

[tool.pyright]
pythonVersion = "3.10"
exclude = [".*", "**/__pycache__/", "*.toml", "*.txt", "*.ini", "**/migrations/"]

[tool.fixit]
python-version = "3.10"
exclude = [".*", "**/__pycache__/", "*.toml", "*.txt", "*.ini", "**/migrations/"]