name: CI/CD pipeline
on:
    push:
        branches:
            - 'main'
jobs:
    DefaultBuild:
        name: Установка репозитория, Python и зависимостей
        runs-on: ubuntu-latest
        steps:
        -   name: Установка репозитория
            uses: actions/checkout@v4.1.6
            with:
                repository: Nikilandgelo/devops_django
        -   name: Установка Python
            uses: actions/setup-python@v5.1.0
            with:
                python-version: '3.10'
                cache: 'pip'
        -   name: Установка зависимостей
            run: pip install -r requirements.txt
        -   name: Проверка кода на синтаксические ошибки
            uses: super-linter/super-linter@v6.5.1
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    LintingCode:
        name: Проверка кода на синтаксические ошибки
        runs-on: ubuntu-latest
        needs: DefaultBuild
        steps:
        -   name: Запуск flake8
            run: flake8 ./3.4-django-testing
    TestingCode:
        name: Создание БД и запуск тестов
        runs-on: ubuntu-latest
        needs: DefaultBuild
        services:
            postgres_db:
                image: postgres:14
                env:
                    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                    POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
                    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                options: >-
                    --health-cmd pg_isready
                    --health_interval 2s
                    --health_retries 5
        steps:
        -   run: cd 3.4-django-testing && python manage.py test
        -   name: Покрытие тестами
            run: cd 3.4-django-testing && pytest --cov=.