name: CI/CD pipeline
on:
    push:
        branches:
            - 'main'
jobs:
    DefaultBuild:
        name: Установка репозитория, Python и зависимостей на выполняемую workflow virtual machine
        runs-on: ubuntu-latest
        steps:
        -   name: Установка репозитория
            uses: actions/checkout@v4
            with:
                repository: Nikilandgelo/devops_django
        -   name: Установка Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.10'
                cache: 'pip'
        -   name: Установка зависимостей
            run: pip install -r requirements.txt
    LintCode:
        name: Проверка кода на синтаксические ошибки
        runs-on: ubuntu-latest
        needs: DefaultBuild
        strategy:
            matrix:
                linter: [flake8, pylint, ruff, mypy, pytype, pyright, fixit, pyre]
        steps:
        -   name: Проверка на синтаксические ошибки используя ${{ matrix.linter }}
            # uses: advanced-security/python-lint-code-scanning-action@v1
            # with:
            #     linter: 
            run: python3 ./python_lint.py ${{ matrix.linter }}
    TestingCode:
        name: Создание БД и запуск тестов
        runs-on: ubuntu-latest
        needs: LintCode
        services:
            postgres_db:
                image: postgres:14
                env:
                    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                    POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
                    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                options: >-
                    --health-cmd 'pg_isready -U $POSTGRES_USER'
                    --health_interval 2s
                    --health_retries 5
        steps:
        -   run: cd 3.4-django-testing && python manage.py test
        -   name: Покрытие тестами
            run: cd 3.4-django-testing && pytest --cov=.